### ISSUE TITLE
无法连接服务器

### ISSUE THREAD

**Issue by imairy** [HankWang95/Multiple-developers-Django-Project#12]
@HankWang95 

ssh连接远程服务器报错。
```bash
root@***: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

可能需要在服务器做些配置：
1. [腾讯云Permission denied (publickey,gssapi-keyex,gssapi-with-mic)](https://www.chengxiaobai.cn/record/tencent-cloud-denied-permission-publickey-gssapikeyex-gssapiwithmic.html)
2. [SSH无法登录-腾讯云官方论坛](http://bbs.qcloud.com/thread-12835-1-1.html)

**Comment by HankWang95** [comment]
ssh -i ./tencent.dms root@140.143.135.225
密钥文件给你
