### ISSUE TITLE
缺少入口

### ISSUE THREAD

**Issue by HankWang95** [HankWang95/Multiple-developers-Django-Project#13]
@imairy 
# navbar 中希望加入以下入口

[通过判断权限实现给不同的角色不同入口](https://segmentfault.com/a/1190000007124746)
## editor
- 名称：审核员通道
- 判断权限：{{ perms.curriculum.editor }}
 `    path('editor/', editor.editor_index_view, name='editor_index'),
`
## student
- 名称：我参加的课程
- student无权限
`    path('my/series_list/', my_series.my_series_list_view, name='my_series_list'),
`

## teacher
- 名称：我发布的系列（url同上）
- 判断权限：{{ perms.curriculum.upload_file }}
`    path('my/series_list/', my_series.my_series_list_view, name='my_series_list'),
`

**Comment by imairy** [comment]
如果有看注意到`navbar.html`的以下片段的话，其实是根据权限分入口的
```html
{% if not request.user.is_active %}
                    
{% if who == 'teachers' %}
    <a class="nav-item nav-link" href="{% url 'my_series_list' %}">我发布的课程</a>
{% elif who == 'students' %}
     <a class="nav-item nav-link" href="{% url 'my_series_list' %}">我参加的课程</a>
{% endif %}
                    
{% if who == 'editors' %}
      <a class="nav-item nav-link" href="#">审核员通道</a>
{% endif %}
{% endif %}
```
理想的情况应该是下面效果
![teacher](https://user-images.githubusercontent.com/4737519/41081325-fc5ee856-6a5c-11e8-92f3-e42f3955d101.jpg)
![student](https://user-images.githubusercontent.com/4737519/41081326-fca11460-6a5c-11e8-8551-b8bbd1d1eb45.jpg)

我是依赖`who`变量来判断分组，但是似乎并不那么好使，稍后修改。

**Comment by HankWang95** [comment]
历史遗留问题，那个接口写的并不是很好应该弃用掉，直接通过权限判断会更好一些。辛苦啦！ @imairy
