### ISSUE TITLE
uwsgi服务如何重启？

### ISSUE THREAD

**Issue by imairy** [HankWang95/Multiple-developers-Django-Project#17]
修改了部分`.py`文件，但是并没有生效

已做以下尝试：
- `nginx -s reload`重启nginx，但`.py`文件的修改仍没生效
- `uwsgi --stop  **.pid`重启uwsgi但没有`.pid`文件

**Comment by HankWang95** [comment]
试试 service uwsgi restart?
或者 lsof -i :8880 查到运行线程，然后 kill -9 线程1 线程2……
没注意到你的issue，不好意思，下次请@我下 @imairy
